import {ListItem} from './page/Me';

export const DATA: ListItem[] = [
  {
    symbol: '1',
    name: '大豪科技',
    price: 20,
    fluctuate: 3.77,
    riseAndFall: 0,
    sumName: '007788',
    type: 'sh',
    prePrice: 22,
    preRiseAndFall: 3.77,
  },
  {
    symbol: '2',
    name: '阿里巴巴',
    price: 20,
    fluctuate: 3.77,
    riseAndFall: 0,
    type: 'hk',
  },
  {
    symbol: '3',
    name: '特斯拉',
    price: 20,
    fluctuate: 3.77,
    riseAndFall: 0,
    type: 'us',
  },
  {
    symbol: '4',
    name: '大豪科技',
    price: 20,
    fluctuate: 3.77,
    riseAndFall: 0,
    sumName: '007788',
    type: 'sh',
    prePrice: 22,
    preRiseAndFall: 3.77,
  },
  {
    symbol: '5',
    name: '大豪科技',
    price: 20,
    fluctuate: 3.77,
    riseAndFall: 0,
    sumName: '007788',
    type: 'sh',
    prePrice: 22,
    preRiseAndFall: 3.77,
  },
  {
    symbol: '6',
    name: '大豪科技',
    price: 20,
    fluctuate: 3.77,
    riseAndFall: 0,
    sumName: '007788',
    type: 'sh',
    prePrice: 22,
    preRiseAndFall: 3.77,
  },
  {
    symbol: '7',
    name: '大豪科技',
    price: 20,
    fluctuate: 3.77,
    riseAndFall: 0,
    sumName: '007788',
    type: 'sh',
    prePrice: 22,
    preRiseAndFall: 3.77,
  },
  {
    symbol: '8',
    name: '大豪科技',
    price: 20,
    fluctuate: 3.77,
    riseAndFall: 0,
    sumName: '007788',
    type: 'sh',
    prePrice: 22,
    preRiseAndFall: 3.77,
  },
  {
    symbol: '9',
    name: '大豪科技',
    price: 20,
    fluctuate: 3.77,
    riseAndFall: 0,
    sumName: '007788',
    type: 'sh',
    prePrice: 22,
    preRiseAndFall: 3.77,
  },
  {
    symbol: '10',
    name: '大豪科技',
    price: 20,
    fluctuate: 3.77,
    riseAndFall: 0,
    sumName: '007788',
    type: 'sh',
    prePrice: 22,
    preRiseAndFall: 3.77,
  },
  {
    symbol: '11',
    name: '大豪科技',
    price: 20,
    fluctuate: 3.77,
    riseAndFall: 0,
    sumName: '007788',
    type: 'sh',
    prePrice: 22,
    preRiseAndFall: 3.77,
  },
  {
    symbol: '12',
    name: '大豪科技',
    price: 20,
    fluctuate: 3.77,
    riseAndFall: 0,
    sumName: '007788',
    type: 'sh',
    prePrice: 22,
    preRiseAndFall: 3.77,
  },
  {
    symbol: '13',
    name: '大豪科技',
    price: 20,
    fluctuate: 3.77,
    riseAndFall: 0,
    sumName: '007788',
    type: 'sh',
    prePrice: 22,
    preRiseAndFall: 3.77,
  },
  {
    symbol: '14',
    name: '大豪科技',
    price: 20,
    fluctuate: 3.77,
    riseAndFall: 0,
    sumName: '007788',
    type: 'sh',
    prePrice: 22,
    preRiseAndFall: 3.77,
  },
  {
    symbol: '15',
    name: '大豪科技',
    price: 20,
    fluctuate: 3.77,
    riseAndFall: 0,
    sumName: '007788',
    type: 'sh',
    prePrice: 22,
    preRiseAndFall: 3.77,
  },
  {
    symbol: '16',
    name: '大豪科技',
    price: 20,
    fluctuate: 3.77,
    riseAndFall: 0,
    sumName: '007788',
    type: 'sh',
    prePrice: 22,
    preRiseAndFall: 3.77,
  },
  {
    symbol: '17',
    name: '大豪科技',
    price: 20,
    fluctuate: 3.77,
    riseAndFall: 0,
    sumName: '007788',
    type: 'sh',
    prePrice: 22,
    preRiseAndFall: 3.77,
  },
];

export enum MarketType {
  US = 'us',
  SH = 'sh',
  HK = 'hk',
  ME = 'me',
}

export const HEADERDATA = [
  {
    title: '自选',
    id: 'me',
    key: 'me',
  },
  {
    title: '美股',
    id: 'us',
    key: 'us',
  },
  {
    title: '港股',
    id: 'us1',
    key: 'us1',
  },
  {
    title: '沪深',
    id: 'us2',
    key: 'us2',
  },
  {
    title: '伦敦',
    id: 'us3',
    key: 'us3',
  },
  {
    title: '新加坡',
    id: 'us4',
    key: 'us4',
  },
  {
    title: '澳洲',
    id: 'us5',
    key: 'us5',
  },
  {
    title: '期货',
    id: 'us6',
    key: 'us6',
  },
];
